### PR TITLE
clean up sentence structure

### PR DESCRIPTION
**Pull request by wvcpw**
Pull request description
------------------------

removed excess commas and broke up sentence in 2 for better readability.

@heyjack88

### CODE REVIEW

**Comment by stdavis** [comment]
@wvcpw: Who is this? Chaz, Jeni or someone else? We want to get you a mouse pad but don't know who to send it to. Are you coming to UGIC?

**Comment by steveoh** [comment]
It's chad bunn. You can see his Twitter name in the pr.

**Comment by wvcpw** [comment]
Haha mystery GIS user at WVC! My name is Chad Bunn. I got hired a year ago
as the Public Works GIS specialist for WVC.  Wish I was coming to UGIC, but
maybe next year.  Love what you guys are doing with the state though and
appreciate all the open data and GitHub promotion.  Modern day GIS skills
for sure.  You can send the mousepad to me at the City Hall address.

On Mon, May 9, 2016 at 9:43 AM, Scott Davis <notifications@github.com>
wrote:

> @wvcpw <https://github.com/wvcpw>: Who is this? Chaz, Jeni or someone
> else? We want to get you a mouse pad but don't know who to send it to. Are
> you coming to UGIC?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/agrc.github.io/pull/112#issuecomment-217902548>
>



-- 
Chad Bunn
GIS & Data Specialist
3600 S. Constitution Blvd.
West Valley City, UT 84119
801-963-3496 (office)

**Comment by todrobbins** [comment]
🐭🗒

**Comment by steveoh** [comment]
@jpechmann get this man a mouse pad!

**Pull request merged**
